building buildspec01

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -8,21 +8,12 @@ phases:
 
   pre_build:
     commands:
-      - echo "Source version (branch) is $CODEBUILD_SOURCE_VERSION"
-      - |
-        case "$CODEBUILD_SOURCE_VERSION" in
-          refs/heads/admin-dev-001)
-            export ENV="dev"
-            ;;
-          refs/heads/main)
-            export ENV="prod"
-            ;;
-          *)
-            echo "Unknown branch ($CODEBUILD_SOURCE_VERSION), aborting deployment."
-            exit 1
-            ;;
-        esac
-      - echo "Environment is $ENV"
+      - echo "Deploying to environment $DEPLOY_ENV"
+      - if [[ -z "$DEPLOY_ENV" ]]; then
+          echo "DEPLOY_ENV not set. Aborting deployment.";
+          exit 1;
+        fi
+      - export ENV=$DEPLOY_ENV
       - echo "Fetching configuration from Parameter Store"
       - export TARGET_BUCKET=$(aws ssm get-parameter --name /spooky-decs/admin/$ENV/s3-bucket --query 'Parameter.Value' --output text)
       - export DISTRIBUTION_ID=$(aws ssm get-parameter --name /spooky-decs/admin/$ENV/cf-distribution --query 'Parameter.Value' --output text)
@@ -39,3 +30,7 @@ phases:
       - echo "Creating CloudFront invalidation"
       - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
       - echo "Deployment complete"
+
+artifacts:
+  files:
+    - '**/*'
